# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: mportal
  pool: 5
  encoding: unicode
  username: postgres
  pssword: postgres

production:
  adapter: postgresql
  database: mportal
  pool: 5
  encoding: unicode
  username: postgres
  pssword: postgres